---
- name: install general requirements
  package:
    name: 
      - epel-release
      - wget
      - vim

- name: Download specific R rpm and 
  get_url:
    url: "https://cdn.rstudio.com/r/centos-7/pkgs/R-{{ R_VERSION }}-1-1.x86_64.rpm"
    dest: "/opt/R-{{ R_VERSION }}-1-1.x86_64.rpm"

- name: install R package
  package:
    name: "/opt/R-{{ R_VERSION }}-1-1.x86_64.rpm"
    state: present
    use: yum

- name: symlink to bin
  file:
    src: '/opt/R/{{ R_VERSION }}/bin/{{ item }}'
    dest: '/usr/bin/{{ item }}'
    state: link
  with_items:
    - R
    - Rscript













 
